In [1]:
import cvxpy

In [38]:
probs = [0.75, 0.15, 0.1]
n = len(probs)
x = cvxpy.Variable(n)
alpha = 0.5
epsilon = 1.0
objective = cvxpy.Minimize(sum([cvxpy.exp(-alpha*x[i])*probs[i] for i in range(n)]))
constraints = [cvxpy.log_sum_exp(x) <= epsilon]
prob = cvxpy.Problem(objective, constraints)

# The optimal objective value is returned by `prob.solve()`.
result = prob.solve()
# The optimal value for x is stored in `x.value`.
print(x.value)

[ 0.52817274 -0.54486084 -0.81525021]


In [39]:
import numpy as np

np.exp((1+alpha)*x.value)/np.sum(np.exp((1+alpha)*x.value))

array([0.75003   , 0.14998913, 0.09998086])

In [35]:
probs = [0.65, 0.15, 0.2]
n = len(probs)
x = cvxpy.Variable(n)
alpha = 0.8
epsilon = 1.1
objective = cvxpy.Minimize(sum([cvxpy.exp(-alpha*x[i])*probs[i] for i in range(n)]) + epsilon * cvxpy.log_sum_exp(x))
#constraints = [cvxpy.log_sum_exp(x) <= epsilon]
prob = cvxpy.Problem(objective)

# The optimal objective value is returned by `prob.solve()`.
result = prob.solve()
# The optimal value for x is stored in `x.value`.
print(x.value)

[-0.09389067 -0.90859756 -0.74876182]


In [36]:
import numpy as np

np.exp((1+alpha)*x.value)/np.sum(np.exp((1+alpha)*x.value))

array([0.65002789, 0.14998614, 0.19998597])